routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('paperimage/{href?}', function ($href=null) {
    // dd(($href));
    return view('frontend/paperimage',compact('href'));
})->name('front.paperimage');

Route::get('epapermain/{date?}/{page?}', 'HomeController@epaper')->name('front.epaper');
Route::post('epapermain/', 'HomeController@epaperdate')->name('front.epaperdate');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/crop', 'HomeController@crop')->name('crop');
Route::post('image', 'HomeController@image')->name('image');
Route::group(['prefix' => 'backend', 'middleware' => ['auth']], function () {
Route::resource('epaperlink', 'EpaperLinkController');
Route::get('epaperlinkdel/{id?}', 'EpaperLinkController@deletesingle')->name('epaperlink.deletesingle');
Route::post('epaperlinkupdate', 'EpaperLinkController@updatelink')->name('epaperlink.updatelink');
Route::resource('epaper', 'EpaperController');
Route::post('epaperdate', 'EpaperController@epaperdate')->name('epaper.date');
Route::post('indexmain/', 'EpaperController@indexmain')->name('epaper.indexmain');
Route::get('managelinks/{id?}', 'EpaperController@managelinks')->name('epaper.managelinks');

});

app/Epaper.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Epaper extends Model
{
     protected $fillable = [
        'title',
        'image',
        'datetime',
        'is_publish',
        'extra1',
        'map_id',
       'created_by',
       'updated_by',
    ];
    public function epaperLinks()
    {
        return $this->hasMany('App\EpaperLink');
    }
}

app/Http/Controllers/EpaperController.php
<?php

namespace App\Http\Controllers;

use DateTime;
use App\Epaper;
use DateTimeZone;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Session;

class EpaperController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function epaperdate(Request $request)
    {
        $epaperdate = $request->datetime;
        return redirect()->route('epaper.create')->withCookie(cookie()->forever('epaperdate', $epaperdate));

    }
    public function indexmain(Request $request)
    {
        // dd($request);
        if ($request->datetime == null) {
            $date = new DateTime("now", new DateTimeZone('Asia/Kathmandu'));
            $date = $date->format('Y-m-d 00:00:00');

        } else {
            $date = strtotime($request->datetime);
            $date = date('Y-m-d 00:00:00', $date);
            // $date = $date->format('Y-m-d 00:00:00');

        }
        // dd($date);
        $epaper = Epaper::where('datetime', $date)->orderBy('id', 'desc')->paginate(20);
        //  $images = Epaper::orderBy('id', 'desc')->get();

        return view('backend.epaper.index', compact('epaper'));
    }
    public function managelinks($id = null)
    {
        // dd($id);
        $data = Epaper::where('id', $id)->first();
        $date=$data->datetime;
        $epapers=Epaper::where('datetime',$date)->get();
        $message="sabin";



                    if (($data->epaperLinks->count())>0)
                    {
                        $message="";




                    }






        // dd($epapers);


        return view('backend.epaper.managelinks', compact('data','epapers','message'));
    }
    public function index()
    {
        $date = new DateTime("now", new DateTimeZone('Asia/Kathmandu'));
        $date = $date->format('Y-m-d 00:00:00');
        $epaper = Epaper::where('datetime', $date)->orderBy('id', 'desc')->paginate(20);
        //  $images = Epaper::orderBy('id', 'desc')->get();

        return view('backend.epaper.index', compact('epaper'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $epaper = new Epaper;
        // dd($epaper);
        return view('backend.epaper.create', compact('epaper'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        // dd($input);
        $title = $request->title;
        $extra1 = $request->extra1;

        // $images = array();

        //    if (!empty($request->file('image'))) {
        //     $file = $request->file('image');
        //     $path = public_path() .'/news_epaper/';
            // if (!file_exists($path)) {
            //     mkdir($path);
            // }
        //     $name = uniqid() . '_' . $file->getClientOriginalName();
        //     $name=str_replace(' ','_',$name);
        //     $image_resize = Image::make($file->getRealPath());
        //     // $dimension=$request->image_dimension;
        //     // $dimtmp=explode('x',$dimension);

        //     $image_resize->resize(500, 600);
        //     if ($image_resize->save($path . $name)) {
        //         $image = $name;
        //         // dd($image);
        //         $input['image'] = $image;
        //     }
        // }

        if (!empty($request->image)) {
            $array_size = (sizeof($request->image));
            foreach ($request->file('image') as $i => $image) {
                if (!empty($image)) {
                    $path = public_path() . '/news_epaper/';
                         if (!file_exists($path)) {
                mkdir($path);
            }
                    $pimage = uniqid() . '_' . $image->getClientOriginalName();
                    $pimage = str_replace(' ', '_', $pimage);
                    $image_resize = Image::make($image->getRealPath());
            // $dimension=$request->image_dimension;
            // $dimtmp=explode('x',$dimension);

            $image_resize->resize(500, 600);
            if ($image_resize->save($path . $pimage)) {
                // $image = $pimage;
                // dd($image);
                // $input['image'] = $pimage;
            // }
                    // if ($image->move($path, $pimage)) {
                        $status = Epaper::create([
                            'image' => $pimage,
                            //    'news_id' => $request->news_id,
                            'datetime' => $request->datetime,
                            'title' => 'page' . $i,
                            //    'extra1' => $extra1,

                        ]);
                    }
                }

            }

        }
        // if (!empty($request->image)) {
        //     $array_size = (sizeof($request->image));
        //     foreach ($request->file('image') as $i => $image) {
        //         if (!empty($image)) {
        //             $path = public_path() . '/news_epaper';
        //             $pimage = uniqid() . '_' . $image->getClientOriginalName();
        //             $pimage = str_replace(' ', '_', $pimage);
        //             if ($image->move($path, $pimage)) {
        //                 $status = Epaper::create([
        //                     'image' => $pimage,
        //                     //    'news_id' => $request->news_id,
        //                     'datetime' => $request->datetime,
        //                     'title' => 'page' . $i,
        //                     //    'extra1' => $extra1,

        //                 ]);
        //             }
        //         }

        //     }

        // }


        return redirect('backend/epaper');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Epaper  $epaper
     * @return \Illuminate\Http\Response
     */
    public function show(Epaper $epaper)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Epaper  $epaper
     * @return \Illuminate\Http\Response
     */
    public function edit(Epaper $epaper)
    {
        return view('backend.epaper.edit', compact('epaper'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Epaper  $epaper
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Epaper $epaper)
    {
        $input = $request->all();
        // dd($input);
        if($request->datetime==null)
        {
            $input['datetime']=$request->datetimetmp;
        }
        // dd($input);


        // $image = '';
        // if (!empty($request->file('image'))) {
        //     $file = $request->file('image');
        //     $path = public_path() . '/news_epaper';
        //     $name = uniqid() . '_' . $file->getClientOriginalName();
        //     $name = str_replace(' ', '_', $name);
        //     if ($file->move($path, $name)) {
        //         $image = $name;
        //         $input['image'] = $image;
        //     }
        // }


        //new way


        if (!empty($request->file('image'))) {
            $file = $request->file('image');
            $path = public_path() .'/news_epaper/';
            if (!file_exists($path)) {
                mkdir($path);
            }
            $name = uniqid() . '_' . $file->getClientOriginalName();
            $name=str_replace(' ','_',$name);
            $image_resize = Image::make($file->getRealPath());
            // $dimension=$request->image_dimension;
            // $dimtmp=explode('x',$dimension);

            $image_resize->resize(500, 600);
            if ($image_resize->save($path . $name)) {
                $image = $name;
                // dd($image);
                $input['image'] = $image;
            }
        }


        $status = $epaper->update($input);
        if ($status) {
            Session::flash('success', 'Information Updated successfully.');
        } else {
            Session::flash('error', 'Information Cannot be Update');
        }
        return redirect('backend/epaper');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Epaper  $epaper
     * @return \Illuminate\Http\Response
     */
    public function destroy(Epaper $epaper)
    {
       $status = $epaper->delete();
        if ($status) {
            $imagepath = public_path() . '/news_epaper' . $epaper->image;
            if (File::exists($imagepath)) {
                File::delete($imagepath);
            }
            // if (File::exists($authorimagepath)) {
            //     File::delete($authorimagepath);
            // }
            Session::flash('success', 'Information deleted successfully.');
        } else {
            Session::flash('error', 'Information cannot be deleted.');
        }
        return redirect('backend/epaper');
    }
}

resources/views/backend/epaper/abitdone.blade.php
@extends('layouts.backmaster')

@section('title', 'data')

@section('content_header')
@stop

@section('csssec')

<script src="https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.7.0/canvasjs.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<style>




</style>
<style>
    .row {
        margin-top: 1em;
    }

</style>
@stop

@section('jssec')
<script>
    $(function () {
        var canvas = document.getElementById("canvas"),
            ctx = canvas.getContext("2d");

        var background = new Image();
        var imgdata = document.getElementById("imagedata");
        // alert(imgdata.value);
        background.src = imgdata.value;

        var img = imgdata.value;

        var width = img.clientWidth;
            var height = img.clientHeight;
            // console.log(width);

        canvas.width = 400;
        canvas.height = 600;

        background.onload = function () {
            ctx.drawImage(background, 0, 0);
            console.log(width);


        }

    });

</script>
<script>
    initDraw(document.getElementById('canvas'));

    function initDraw(canvas) {
        function setMousePosition(e) {
            var ev = e || window.event; //Moz || IE
            if (ev.pageX) { //Moz
                mouse.x = ev.pageX;
                //+ window.pageXOffset;
                mouse.y = ev.pageY;
                // + window.pageYOffset;
            } else if (ev.clientX) { //IE
                mouse.x = ev.clientX;
                //+ document.body.scrollLeft;
                mouse.y = ev.clientY;
                //+ document.body.scrollTop;
            }
        };

        var mouse = {
            x: 0,
            y: 0,
            startX: 0,
            startY: 0
        };
        var element = null;
        var add = '';

        canvas.onmousemove = function (e) {
            setMousePosition(e);
            if (element !== null) {
                element.style.width = Math.abs(mouse.x - mouse.startX) + 'px';
                element.style.height = Math.abs(mouse.y - mouse.startY) + 'px';
                element.style.left = (mouse.x - mouse.startX < 0) ? mouse.x + 'px' : mouse.startX + 'px';
                element.style.top = (mouse.y - mouse.startY < 0) ? mouse.y + 'px' : mouse.startY + 'px';

                // add='<area shape="rect"' + 'coords='+coorde +" "+ 'alt="Sun" href="sun.htm" >';
                //console.log(add);




            }
        }

        canvas.onclick = function (e) {
            if (element !== null) {
                element = null;
                canvas.style.cursor = "default";
                console.log("finsihed.");
                var x = mouse.startX;
                var y = mouse.startY;
                var x1 = mouse.x;
                var y1 = mouse.y;
                var coorde = x + ',' + y + ',' + x1 + ',' + y1;
                add = '<area shape="rect"' + 'coords=' + coorde + " " + 'alt="Sun" href="sun.htm" >';
                width = Math.abs(mouse.x - mouse.startX);
                height = Math.abs(mouse.y - mouse.startY);
                left = (mouse.x - mouse.startX < 0) ? mouse.x  : mouse.startX;
                var top = (mouse.y - mouse.startY < 0) ? mouse.y : mouse.startY;
                // alert(top);
                // top = (mouse.y - mouse.startY < 0) ? mouse.y : mouse.startY;
                // var rectangleimage = left + ',' + top + ',' + width + ',' + height;
                // console.log(rectangleimage);



                drawrect(left,top,width,height);
                //$('#bigthings').appendChild(add)
                //   bigthings.appendChild(add)
            } else {
                console.log("begun.");
                mouse.startX = mouse.x;
                mouse.startY = mouse.y;
                element = document.createElement('div');
                element.className = 'rectangle'
                element.style.left = mouse.x + 'px';
                element.style.top = mouse.y + 'px';

                canvas.appendChild(element)
                canvas.style.cursor = "crosshair";
            }
        }
    }

    function drawrect(left,top,width,height) {
        // alert(rectangleimage);
        var c = document.getElementById("canvas");
        var ctx = c.getContext("2d");
        ctx.fillStyle = "#f00";
        ctx.fillRect(left,top,width,height);
    }

</script>
<script>
    $('.multi-field-wrapper').each(function () {
        var $wrapper = $('.multi-fields', this);
        $(".add-field", $(this)).click(function (e) {
            var a = $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find(
                'select').val('').focus();
            //a.attr('id','abcd');

        });
        $('.multi-field .remove-field', $wrapper).click(function () {
            if ($('.multi-field', $wrapper).length > 1)
                $(this).parent('.multi-field').remove();
        });
    });

</script>
@stop

@section('content')
{{-- <div id="canvas"> --}}
{{-- <div id="canvas-wrapper"> --}}
    <canvas id="canvas" style="border:1px solid #000"></canvas>
{{-- </div> --}}
{{-- <canvas id="canvas"> --}}
{{-- <img  src="{{asset('/news_epaper/'.$data->image)}}" alt="The Giant Prawn at Ballina" usemap="#bigthings" /> --}}
{{-- </canvas> --}}
<input type="hidden" value="{{asset('/news_epaper/'.$data->image)}}" id="imagedata">
{{-- </div> --}}

{{-- maps --}}
{{-- <map name="bigthings" id="bigthings">


    <area title="area selected already" shape="rect" onmouseover="this.focus();" onmouseout="this.blur();" id="star"
        coords="300,80,516,250" href="#" alt="The VW Kombi, another Aussie icon" />
</map> --}}


{{-- <div class="row">
    <div
        class="col-md-10 col-lg-10 col-xl-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1 col-xs-offset-0 col-sm-offset-0 col-xl-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading padding-bottom">
                <div class="row" style="padding:10px">
                    <table style="width:100%">
                        <tr>
                            <th class="headtext">
                                data
                            </th>
                            <th class=" pull-right">
                                <a href="{{route('epaper.index')}}" class="btn btn-primary pull-right">data List</a>
</th>
</tr>
</table>

</div>
</div>

<div class="panel-body" style="overflow: auto">
    <form action="{{route('epaper.store')}}" method="POST" enctype="multipart/form-data" id="valid_form">


        {{csrf_field()}}




        <div class="multi-fields">
            <div class="multi-field-wrapper">
                <div class="col-md-2 col-md-offset-10">
                    <button type="button" class="add-field btn btn-success"><i class="fa fa-plus"> Add More
                            Field</i>
                    </button>
                </div>
                <br>
                <hr>
                <br>
                <div class="multi-fields">
                    <div class="multi-field">


                        <button style="width:40px; float:right;" type="button"
                            class="remove-field btn btn-danger form-control col-md-2 col-lg-2"><i
                                class="fa fa-times"></i>
                        </button>

                        <br>
                    </div>
                </div>

            </div>
            <hr style="border:solid 2px black">
            <div class="row" style="padding:10px">
                <table style="width:100%">
                    <tr>
                        <th> </th>
                        <th class=" pull-right">
                            <button class="btn btn-success form-control">Submit</button> </th>
                    </tr>
                </table>

            </div>
    </form>
</div>
</div>
</div>
</div> --}}

@stop

resources/views/backend/epaper/create.blade.php
@extends('layouts.backmaster')

@section('title', 'epaper')

@section('content_header')
@stop

@section('csssec')
<style>
    .row {
        margin-top: 1em;
    }

</style>
@stop

@section('jssec')
<script>
    $('.multi-field-wrapper').each(function () {
        var $wrapper = $('.multi-fields', this);
        $(".add-field", $(this)).click(function (e) {
            var a = $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find(
                'select').val('').focus();
            //a.attr('id','abcd');

        });
        $('.multi-field .remove-field', $wrapper).click(function () {
            if ($('.multi-field', $wrapper).length > 1)
                $(this).parent('.multi-field').remove();
        });
    });

</script>
@stop

@section('content')

<div class="row">
    <div
        class="col-md-10 col-lg-10 col-xl-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1 col-xs-offset-0 col-sm-offset-0 col-xl-offset-1">
        <div class="panel panel-default">
            <div class="panel-heading padding-bottom">
                <div class="row" style="padding:10px">
                    <table style="width:100%">
                        <tr>
                            <th class="headtext">
                                Epaper
                            </th>
                            <th class=" pull-right">
                                <a href="{{route('epaper.index')}}" class="btn btn-primary pull-right">epaper List</a>
                            </th>
                        </tr>
                    </table>

                </div>
            </div>

            <div class="panel-body" style="overflow: auto">
                <form action="{{route('epaper.store')}}" method="POST" enctype="multipart/form-data" id="valid_form">


                    {{csrf_field()}}
                    {{-- @if($epaper)

                    @foreach($epaper as $item)

                    <img src="{{asset('/news_epaper/'.$item->image)}}" height="100" width="150">

                    @endforeach
                    <h1>Add More Images</h1>
                    @endif --}}

                    <div class="multi-fields">
                        <div class="multi-field-wrapper">
                            {{-- <div class="col-md-2 col-md-offset-10">
                                <button type="button" class="add-field btn btn-success"><i class="fa fa-plus"> Add More
                                        Field</i>
                                </button>
                            </div> --}}
                            <br>
                            <hr>
                            <br>
                            <div class="multi-fields">
                                <div class="multi-field">
                                    <div class="row">
                                        <div class="col-md-6 col-xs-12">
                                            <div class="form-grpup">
                                                <label>Upload Image</label>
                                                <input type="file" name="image[]" multiple class="form-control"
                                                    placeholder="Image" value="">
                                            </div>
                                        </div>
                                         <div class="col-md-6 col-xs-12" id="publish-time">
                                            <div class="form-group">
                                                <label>Publishing Date</label>
                                                <input type="date" name="datetime" class="form-control" required
                                                    placeholder="Time" value="{{old('datetime')}}">

                                            </div>
                                        </div>
                                        {{-- <div class="col-md-6 col-xs-12">
                                            <div class="form-grpup">
                                                <label>Title</label>
                                                <input type="text" name="title" class="form-control" placeholder="page1"
                                                    value="{{old('title')}}">

                                            </div>
                                        </div> --}}
                                    </div>
                                    {{-- <input type="hidden" readonly name="news_id" class="form-control"
                                        placeholder="News ID" value="{{ Cookie::get('news_id') }}"> --}}
                                    <div class="row">
                                        {{-- <div class="col-md-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Description</label>
                                                <textarea type="text" name="extra1" class="form-control"
                                                    placeholder="Image Description">{{old('extra1')}}</textarea>
                                            </div>
                                        </div> --}}
                                        {{-- <div class="col-md-6 col-xs-12" id="publish-time">
                                            <div class="form-group">
                                                <label>Publishing Date</label>
                                                <input type="date" name="datetime" class="form-control" required
                                                    placeholder="Time" value="{{old('datetime')}}">

                                            </div>
                                        </div> --}}
                                        {{-- <button style="width:40px; float:right;" type="button"
                                        class="remove-field btn btn-danger form-control col-md-2 col-lg-2"><i
                                            class="fa fa-times"></i>
                                    </button> --}}

                                        <br>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <hr style="border:solid 2px black">
                        <div class="row" style="padding:10px">
                            <table style="width:100%">
                                <tr>
                                    <th> </th>
                                    <th class=" pull-right">
                                        <button class="btn btn-success form-control">Submit</button> </th>
                                </tr>
                            </table>

                        </div>
                </form>
            </div>
        </div>
    </div>
</div>

@stop

resources/views/backend/epaper/index.blade.php
@extends('layouts.backmaster')

@section('title', 'epaper')

@section('content_header')
@stop

@section('csssec')
@stop

@section('jssec')
<script>
     $("#widgetFieldInput").change(function () {
        this.form.submit();
    });
</script>
@stop

@section('content')
{{-- <div class="container"> --}}
<div class="row" >
    <div class="col-md-10 col-lg-10 col-xl-10 col-sm-12 col-xs-12 col-lg-offset-1 col-md-offset-1 col-xs-offset-0 col-sm-offset-0 col-xl-offset-1">
    {{-- <div class="col-md-10 col-lg-10 col-xl-10  col-lg-offset-1 col-md-offset-1  col-xl-offset-1"> --}}
        {{-- <div> --}}
        <div class="panel panel-default">
            <div class="panel-heading padding-bottom">
                <div class="row" style="padding:5px">
                    <table style="width:100%">
                        <tr >
                            {{-- <th class="headtext">epaper</th> --}}
                            <th ><a href="{{route('epaper.create')}}" class="btn btn-primary ">Add Images </a></th>
                            <th class="pullright-">
                        <form action="{{route('epaper.indexmain')}}" method="post">
                            {{csrf_field()}}
                            <label class="pull-right"> Search by date</label>
                            <input type="date" class="pull-right" id="widgetFieldInput" value="" name="datetime"
                                >

                            </th>

                        </form>
                        </tr>

                    </table>
                    {{-- <div class="col-xs-10">
                        <h1>epaper</h1>
                    </div>
                    <div class="col-xs-1 padding-top">
                        <a href="{{route('epaper.create')}}" class="btn btn-primary pull-right">Add Images </a>
                    </div> --}}
                </div>
                {{-- <label>Comment List</label> --}}
            </div>
            <div class="panel-body" style="overflow: auto">
                @if(Session::has('success'))
                <div class="alert alert-success">
                    {{ Session::get('success') }}
                </div>
                @endif
                @if(Session::has('error'))
                <div class="alert alert-danger">
                    {{ Session::get('error') }}
                </div>
                @endif

                <table class="table table-bordered" id="datatable">
                    <thead>
                        <tr>
                            <th>S.N.</th>
                            <th>Image Credit</th>
                            <th>Image</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($epaper as $i=>$eachimage)
                        <tr>
                            <td>{{$i+1}}</td>
                            <td>{{$eachimage->title}}</td>
                            <td>
                                <img src="{{asset('/news_epaper/'.$eachimage->image)}}" height="100" width="150">

                            </td>

                                         <td>
                                <a href="{{route('epaper.edit', $eachimage->id)}}" data-toggle="tooltip" title="Edit Information" class="btn btn-primary"><i class="fa fa-pencil"> </i></a>
                                {{-- <a href="{{route('epaper.show', $eachimage->id)}}" data-toggle="tooltip" title="View Detail" class="btn btn-success"><i class="fa fa-eye"></i></a> --}}

                                <form action="{{route('epaper.destroy', $eachimage->id)}}" method="POST" onsubmit="return confirm('Are You Sure??')" style="display: inline;">
                                    <input type="hidden" name="_method" value="delete" >
                                    {{csrf_field()}}
                                        <button type="submit" class="btn btn-danger" data-toggle="tooltip" title="Delete Information" ><i class="fa fa-trash"></i></button>
                                </form>
                                <a href="{{route('epaper.managelinks', $eachimage->id)}}" data-toggle="tooltip" title="Manage Links" class="btn btn-info"><i class="fa fa-link"> </i></a>

                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {{-- </div> --}}
</div>
@stop